CREATE DATABASE school;  
DROP DATABASE school;


CREATE DATABASE college;
USE college;

CREATE TABLE student(
id INT PRIMARY KEY,
NAME VARCHAR(50),
age INT NOT NULL);

INSERT INTO student VALUES(1, "PRANAV", 17);
INSERT INTO student VALUES(2, "KUSUM", 29);
INSERT INTO student VALUES(3, "KUMAR", 28);
INSERT INTO student VALUES(4, "SHRAVANEE", );

SELECT * FROM student;




